"""empty message

Revision ID: 4d6f7d185b80
Revises: c254d3fa999b
Create Date: 2019-11-05 00:16:29.566486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d6f7d185b80'
down_revision = 'c254d3fa999b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'author_user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author_user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'books', 'users', ['author_user_id'], ['id'])
    # ### end Alembic commands ###
