"""empty message

Revision ID: f0a1fd299fe5
Revises: 39d9d94473cf
Create Date: 2019-11-11 20:47:26.525030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0a1fd299fe5'
down_revision = '39d9d94473cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('length_minutes', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('religious_verses', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('theme', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'theme')
    op.drop_column('appointments', 'religious_verses')
    op.drop_column('appointments', 'length_minutes')
    # ### end Alembic commands ###
